#!/usr/bin/env bash
#
# Write target.env (gitignored) from the outputs of the KCP-generated target_infra
# Terraform: the Enterprise cluster's IDs, its private bootstrap and REST endpoints, and
# the cluster API key. ~/.bashrc sources target.env in every new shell on the bastion.
#
# Run from anywhere on the bastion after `terraform -chdir=target_infra apply` (STEP-2).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${ROOT_DIR}/target_infra"
OUT="${ROOT_DIR}/target.env"
CLUSTER_LINK_NAME="${CLUSTER_LINK_NAME:-oss-to-cc-link}"

if [ ! -f "${TF_DIR}/terraform.tfstate" ]; then
  echo "ERROR: no Terraform state in ${TF_DIR}. Apply the target infrastructure first."
  exit 1
fi

output() { terraform -chdir="${TF_DIR}" output -raw "$1"; }

bootstrap="$(output cluster_bootstrap_endpoint)"
rest="$(output cluster_rest_endpoint)"

umask 077
{
  echo "# Generated by kcp/write_target_env.sh from the target_infra Terraform outputs."
  printf 'export TARGET_ENV_ID=%q\n' "$(output environment_id)"
  printf 'export TARGET_CLUSTER_ID=%q\n' "$(output cluster_id)"
  printf 'export TARGET_REST_ENDPOINT=%q\n' "${rest%/}"
  printf 'export CC_BOOTSTRAP_SERVERS=%q\n' "${bootstrap#SASL_SSL://}"
  printf 'export CC_API_KEY=%q\n' "$(output kafka_api_key_id)"
  printf 'export CC_API_SECRET=%q\n' "$(output kafka_api_key_secret)"
  printf 'export CLUSTER_LINK_NAME=%q\n' "${CLUSTER_LINK_NAME}"
  echo '# Consumed by the KCP-generated migration-infra and migrate_topics Terraform.'
  echo 'export TF_VAR_confluent_cloud_cluster_api_key="$CC_API_KEY"'
  echo 'export TF_VAR_confluent_cloud_cluster_api_secret="$CC_API_SECRET"'
} > "${OUT}"

echo "Wrote ${OUT}. Load it into this shell with:  source ${OUT}"
