#!/bin/bash
# Interactive deploy wrapper. Prompts for optional migration tracks,
# writes features.auto.tfvars (loaded automatically by Terraform),
# then optionally runs terraform init+apply.
#
# Power users can skip this script and run terraform directly — either by
# editing terraform.tfvars or passing -var flags.

set -euo pipefail

cd "$(dirname "$0")"

echo "================================================================"
echo " Workshop deploy — choose optional migration tracks"
echo "================================================================"
echo
echo "The core topic-migration flow always runs. The following tracks"
echo "are optional and will be enabled only if you select them. Each"
echo "track adds AWS resources and cost."
echo

ask() {
  local prompt="$1"
  local answer
  read -rp "$prompt [y/N]: " answer
  if [[ "${answer:-N}" =~ ^[Yy] ]]; then
    echo "true"
  else
    echo "false"
  fi
}

ACL=$(ask "Enable ACL migration track?")
SCHEMA=$(ask "Enable Schema Registry migration track? (provisions AWS Glue)")
CONN=$(ask "Enable Connector migration track? (provisions MSK Connect + S3 buckets)")

cat > features.auto.tfvars <<EOF
# Generated by deploy.sh — re-run the script to change.
enable_acl_migration       = $ACL
enable_schema_migration    = $SCHEMA
enable_connector_migration = $CONN
EOF

echo
echo "Wrote features.auto.tfvars:"
sed 's/^/  /' features.auto.tfvars
echo

read -rp "Run 'terraform init && terraform apply' now? [Y/n]: " GO
if [[ ! "${GO:-Y}" =~ ^[Nn] ]]; then
  terraform init -input=false
  terraform apply -auto-approve
else
  echo "Skipped. Run 'terraform init && terraform apply' when ready."
fi
